INSERT INTO equipos (categoria, existencia, nombre, descripcion, marca, modelo, subcategoria) VALUES
('laboratorio_central', 1, 'PRENSA DE COMPRESION HIDRAULICA DE OPERACIÓN ELECTRICA DE 90,000 kgf.', 'con capacidad para pruebas de carga y flexión equipada con manómetro digital, con registro de carga máxima, cuenta con bomba eléctrica de velocidad variable de 2 a 30" cúbicos por minuto, cuenta con certificado de calibración', 'DAVI', '150L/D-002291', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 1, 'PRENSA DE 120 TN CON MANOMETRO ANALOGO, BOMBA MANUAL DE DOBLE PASO', 'prensa para compresion y flexion equipada con manometro analogo de 200 kg de resolucion y bomba de operación manual de doble paso', 'ALCON', 'D0200/D', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 5, 'MASCARILLA RESPIRADOR', 'equipo de proteccion de gases', '3M', '', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 8, 'CARTUCHO CONTRA VAPORES ORGANICOS/GASES ÁCIDOS', 'equipo de proteccion de gases', '3M', '6003', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 6, 'CONO PARA REVENIMIENTO', 'CONO DE ABRAMS Cono truncado con 20 cm de diámetro para base inferior, 10 cm en la base superior y 3 cm de altura provisto de dos estribos para pisar y dos agarraderas para levantar', 'DAVI', '', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 6, 'VARILLA DE COMPACTACIÓN', 'Barra de acero de sección circular, recta, lisa, de 16 mm (5/8") de diámetro y 60 cm de longitud.', 'S/M', '', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 6, 'CUCHARA DE ALBAÑIL', 'Cuchara de 3" de forma triangular', 'SURTEK', '', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 30, 'MOLDES PARA PROBETAS DE CONCRETO', 'Molde cilindrico metalico de 15 x 30 cm con tapa y asas, base maquinada.', 'DAVI', '', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 1, 'EQUIPO UNIVERSAL PARA FLEXION DE VIGAS', 'EQUIPO PARA PRENSA HIDRAULICA para ensayos de especimenes de concreto a flexión por MR (módulo de resistencia a la flexión)', 'ELVEC', 'H87', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 4, 'MOLDES METALICOS PARA FLEXION DE VIGAS', 'MOLDES METALICOS DE 15 X 15 X 50 CM', 'ELVEC', 'H88', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 2, 'OLLA ELECTRICA PARA FUNDIR AZUFRE', 'Olla electrica para fundir azufre, para cabecear cilindros de concreto', 'DAVI', 'VS8', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 3, 'ALMOHADILLA DE NEOPRENO', '', 'S/M', '', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 2, 'CONO PARA ENSAYO GRADO DE COMPACTACION', 'Consiste en una seccion desmontable constituida por dos conos metalicos truncados de distintos tamaños unidos por su parte de menor diametro mediante una valvula', 'S/M', '', 'ENSAYO: GRADO DE COMPACTACION DE TERRAPLENES'),
('laboratorio_central', 2, 'FRASCO PARA LA ARENA', 'Frasco de plastico de capacidad aproximada de 4L cuya boca de botella sea compatible con el cono de menor diametro del dispositivo CONO PARA ENSAYO GRADO DE COMPACTACION', 'S/M', '', 'ENSAYO: GRADO DE COMPACTACION DE TERRAPLENES'),
('laboratorio_central', 2, 'PLACA CON ORIFICIO', 'Placa metalica cuadrada con un orificio en el centro como diametro que el cono mas grande del dispositivo CONO PARA ENSAYO GRADO DE COMPACTACION como diametro interior permitiendo un sellado hermetico evitando fugas de arena', 'DAVI', '', 'ENSAYO: GRADO DE COMPACTACION DE TERRAPLENES'),
('laboratorio_central', 2, 'ARENA SILICA DE OTAWA (20-30) SACO DE 50 LB (22.70 KG)', 'arena silica 20-30 para realizar las pruebas de compactacion', 'ELVEC', 'AR-2005', 'ENSAYO: GRADO DE COMPACTACION DE TERRAPLENES'),
('laboratorio_central', 2, 'JARRA DE MANO PARA DISTRIBUIR AZUFRE', 'Jarra metalica, Hecha a base de lamina calibre 16. Diámetro Interior de 15 Centimetros. Altura 30 Centimetros. Capacidad de 5 Litros', 'ALCON', 'D0755', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 4, 'MORTERO DE AZUFRE PARA CABECEAR CILINDROS DE CONCRETO (BULTO 50 LB)', 'Granular Resist. De 700Kg/Cm2 Saco De 25 Kg Fab. Nacional Uso: Material utilizado para cabeceo de cilindro SKU: SL-MA2', 'FORNEY', 'D5000E', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 2, 'CABECEADOR PARA CILINDRO DE CONCRETO (15 X 30 CM) 6" X 12" ASTM C31, C39, C192 AASHTO', 'El Equipo para Cabecear Cilindros viene con 2 Platos (Bases) para especimenes de concreto de 150, 100 y 75 mm de dia.', 'DAVI', 'D0275A', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 2, 'PLATO CABECEADOR 15 X 30 ASTM C617, C31, C192, AASHTO T23 T126', 'plato para cabeceador de cilindros de concreto de 15 x 30 cm', 'DAVI', 'D0278A', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 4, 'EQUIPO DE REVENIMIENTO NMX-C-156-ONNCE-1997', 'cono, cucharon , varillade 5/16", de punta redonda , y base de placa de 3/4" de 0.40 x 0.40 m.', 'DAVI', 'D0530P', 'ENSAYO: CONCRETOS'),
('laboratorio_central', 1, 'PRENSA CBR ELECTRICA DIGITAL', 'Capacidad 5t resolucion 1 kgf, manometro digital para prensa V.R.S. (CBR) incluye display digital celda de craga con 4500 kg de capacidad y resolucion de 1 kg', 'DAVI', 'D1239', 'ENSAYO: ASFALTOS'),
('laboratorio_central', 1, 'PRENSA MARSHALL ELÉCTRICA EQUIPADA.', 'Motor 1 HP, anillo de 5T de capacidad indicador mitutoyo, baño maria, pedestal de madera, sujetador, collarin, base, 3 moldes, mordazaporta indicador', 'ALCON', 'PM-2824-14', 'ENSAYO: ASFALTOS'),
('laboratorio_central', 1, 'MAQUINA DE DESGASTE DE LOS ANGELES', 'Con contador y paro automatico, selector de numero de revoluciones , incluye 12 cargas abrasivas, y cabina aislante de ruidos', 'SEPMI', '', 'ENSAYO: AGREGADOS PETREOS'),
('laboratorio_central', 1, 'HORNO DE CONVECCION FORZADA CON TERMOSTATO DIGITAL 110 V', '60 Hz monofasico de 3 entrepaños dimensiones de las materiales 436X 435 X 500 mm', 'SEPMI', '', 'ENSAYOS DIVERSOS'),
('laboratorio_central', 1, 'BAÑO MARIA ELECTRICO', 'Equipo para mantener muestras asfalticas en agua a temperatura graduada por tiempo definido', 'ALCON', '', 'ENSAYO: ASFALTOS'),
('laboratorio_central', 2, 'TROMPA DE ELEFANTE', 'Embudó para volumen (trompa de Elefante con válvula), dispositivo para colocar la arena en el seno, fabricado en lamina y tubo flexible de espesor 3.5 kg capacidad 9 kg', 'ALCON', '', 'ENSAYO: TERRACERIAS'),
('laboratorio_central', 1, 'BASCULA MECANICA', '', 'sin marca', '', 'ENSAYO: TERRACERIAS'),
('laboratorio_central', 1, 'KIT EQUIVALENTES DE ARENA', '(4 probetas de acrilico transparente, 3 tapas, tapones de hule,tubo irrigador, pisón, capsulas, embudos de distintos tamaños)', 'DAVI', '', 'ENSAYO: CALIDAD DE AGREGADOS PETREOS'),
('laboratorio_central', 1, 'EQUIPO DE MEDICIÓN DE EXPANSIÓN', 'placa perforada con diametro de 149.23 mm a 150.81 mm, con vástago de altura ajustable, tripode para determinación de expansión, extensómetro de carátula', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 6, 'MOLDES CILINDRICOS DE ACERO', '3 moldes cilindricos de acero con diametro interior de 152.4+-0.66 mm con altura de 177.8+- 0.46mm, Provisto cada uno con un collarin de extensión, base para acoplar los moldes de altura ajustable, placa', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 8, 'DISCO ESPACIADOR', 'De un diametro de 150.8+-0.8 mm y altura de 61.4+-0.13mm, Provisto de un maneral desmontable', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 8, 'PLACAS DE CARGA O', 'Dos placas anulares de diametro 149.23 a 150.81 con un orificio central de aprox 54 mm de diametro y de una masa de 4.54+-0.02 kg', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 8, 'PLACAS DE CARGA U', 'Dos placas ranuradas con 149.23 +-1.6mm de diametro con una masa de 2.27 +- 0.02 kg la ranura tendra un ancho de 54.00mm', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 2, 'MORDAZA MARSHALL', '', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 1, 'BASE PARA LABRAR MUESTRA PARA PRUEBA MARSHALL', '', '', '', 'ENSAYO: TERRACERIAS ( VALOR DE SOPORTE DE CALIFORNIA CBR)'),
('laboratorio_central', 1, 'BASCULA DIGITAL', 'capacidad 6kg', 'ESCALI/ANTAR', '136DK', 'ENSAYOS DIVERSOS'),
('laboratorio_central', 5, 'REVELADOR D101-A DYE PENETRANT INSPECTION', 'Producto en aerosol', 'CANTESCO', '340GR', 'ENSAYO: LIQUIDOS PENETRANTES'),
('laboratorio_central', 5, 'LIMPIADOR C-101A DYE PENETRANT INSPECTION', 'Producto en aerosol', 'CANTESCO', '325GR', 'ENSAYO: LIQUIDOS PENETRANTES'),
('laboratorio_central', 5, 'LIQUIDO PENETRANTE P101S-A DYE PENETRANT INSPECTION', 'Producto en aerosol', 'CANTESCO', '354GR', 'ENSAYO: LIQUIDOS PENETRANTES'),
('laboratorio_central', 12, 'BOTELLAS DE DIFERENTE MEDIDAS CON CAPACID ENTRE 750ml A 1.5Lts', '', '', '', 'ENSAYOS DIVERSOS'),
('laboratorio_central', 3, 'MATRAZ VOLUMETRICO 500ml', 'Clase B', 'KIMAX', 'KIMBLE 28015', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 1, 'PICNOMETRO CHAPMAN 450ml', '', 'ALCON', '', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 2, 'PIPETA VOLUMETRICA 50 ML', 'CLASE B', 'KIMAX', 'NO.37000', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 1, 'ANALIZADOR DE CLORO LIBRE', '', 'LAMOTTE', 'CODE XX0130', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 4, 'TERMOMETRO INFRAROJO', '', 'LEMI', 'LEMI-2081', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 1, 'TERMOMETRO DE MERCURIO', 'TOTAL INMERSION', 'TITAN', '55010', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 1, 'INDICADOR DIAL', 'LECTURA 0.01 mm RANGO 0-25mm', 'ALCON', '', 'ENSAYO: DENSIDAD DE MATERIALES FINOS'),
('laboratorio_central', 3, 'COPA CASA GRANDE', 'Calibrada para una altura de caida de 1cm', 'ANTARES', '', 'ENSAYO: LIMITES DE ATERBERG'),
('laboratorio_central', 2, 'CUENTA GOTAS', '', '', '', 'ENSAYO: LIMITES DE ATERBERG'),
('laboratorio_central', 7, 'VIDRIOS DE RELOJ', 'Refractarios para el secado de material', '', '', 'ENSAYO: LIMITES DE ATERBERG'),
('laboratorio_central', 2, 'PLACA DE VIDRIO', 'Con dimensiones minimas de 40*40 por lado y un espesor de 0.6cm', '', '', 'ENSAYO: LIMITES DE ATERBERG'),
('laboratorio_central', 2, 'ALAMBRE DE ACERO', 'De 3mm de diametro y 10cm de longitud.', '', '', 'ENSAYO: LIMITES DE ATERBERG'),
('laboratorio_central', 15, 'MOLDES CAPSULA CON TAPA', 'De aluminio con 4.50mm de alto y 58.8 de diametro interior', '', '', 'ENSAYO: LIMITES DE ATERBERG'); 